import "server-only";
import { db } from "@/lib/db/client";
import type { Prisma } from "@/lib/generated/prisma/client";
import { getProvider } from "@/lib/ai/provider";
import { saveMemory } from "@/lib/ai/workforce/memory";
import { checkFinding, paramsSummary, RESEARCH_SECTIONS, type Finding, type ResearchParams, type ResearchSection } from "./research-rules";

const json = (v: unknown) => JSON.parse(JSON.stringify(v ?? null)) as Prisma.InputJsonValue;
export const RESEARCH_OWNER = "intel-director";

export const parseFindings = (v: unknown): Finding[] => (Array.isArray(v) ? (v as Finding[]).filter((f) => f && typeof f.statement === "string") : []);

export async function addFinding(researchId: string, f: { section?: string; statement?: string; label?: string; sourceUrl?: string | null; sourceTitle?: string | null }) {
  const err = checkFinding(f);
  if (err) return { ok: false as const, error: err };
  const r = await db.marketResearch.findUnique({ where: { id: researchId }, select: { findings: true, status: true } });
  if (!r) return { ok: false as const, error: "Unknown researchId." };
  if (r.status === "COMPLETED") return { ok: false as const, error: "This research is already completed." };
  const list = parseFindings(r.findings);
  if (list.length >= 150) return { ok: false as const, error: "Finding limit reached (150)." };
  list.push({ section: f.section as ResearchSection, statement: f.statement!.trim().slice(0, 1500), label: f.label as Finding["label"], sourceUrl: f.sourceUrl ?? null, sourceTitle: f.sourceTitle?.slice(0, 200) ?? null, at: new Date().toISOString() });
  await db.marketResearch.update({ where: { id: researchId }, data: { findings: json(list), status: "RUNNING", blockedReason: null } });
  return { ok: true as const, count: list.length };
}

/** Completes the research: summary, Knowledge Base draft (for human review) and company memory for other employees. */
export async function completeResearch(researchId: string, summary: string, authorId: string | null) {
  const r = await db.marketResearch.findUnique({ where: { id: researchId } });
  if (!r) return { ok: false as const, error: "Unknown researchId." };
  if (r.status === "COMPLETED") return { ok: true as const, articleId: r.knowledgeArticleId };
  const findings = parseFindings(r.findings);
  if (!findings.length) return { ok: false as const, error: "Record findings first (recordMarketFinding)." };
  const body = [
    `# ${r.title}`,
    `_Parameters: ${paramsSummary(r.params as ResearchParams)}_`,
    "",
    "## Executive summary",
    summary.trim(),
    ...Object.entries(RESEARCH_SECTIONS).flatMap(([k, label]) => {
      const items = findings.filter((f) => f.section === k);
      return items.length ? ["", `## ${label}`, ...items.map((f) => `- **${f.label}** — ${f.statement}${f.sourceUrl ? ` ([${f.sourceTitle || "source"}](${f.sourceUrl}))` : ""}`)] : [];
    }),
    "",
    "_Generated by the AI Market Intelligence department. Review before publishing._",
  ].join("\n");
  const slug = `market-research-${researchId}`.toLowerCase();
  const article = await db.knowledgeArticle.upsert({ where: { slug }, update: { body, excerpt: summary.slice(0, 280) }, create: { slug, title: r.title.slice(0, 200), excerpt: summary.slice(0, 280), body, category: "COMPANY", tags: ["market-research"], visibility: "INTERNAL", status: "DRAFT", authorId } });
  await db.marketResearch.update({ where: { id: researchId }, data: { status: "COMPLETED", summary: summary.slice(0, 20_000), knowledgeArticleId: article.id, completedAt: new Date() } });
  await saveMemory({ agentSlug: RESEARCH_OWNER, kind: "KNOWLEDGE", scope: "COMPANY", title: `Market research: ${r.title}`.slice(0, 200), content: `${summary.slice(0, 3000)}\nFull findings with sources: /admin/marketing/market/${researchId}`, expiresInDays: 365 });
  return { ok: true as const, articleId: article.id };
}

/** Keeps the research status in step with its task (e.g. the task failed, or the provider was connected later). */
export async function syncResearch(id: string) {
  const r = await db.marketResearch.findUnique({ where: { id } });
  if (!r || !r.taskId || r.status === "COMPLETED") return r;
  const t = await db.aITask.findUnique({ where: { id: r.taskId }, select: { status: true, error: true } });
  let status = r.status;
  let blockedReason = r.blockedReason;
  if (t?.status === "FAILED" || t?.status === "CANCELLED") {
    status = "FAILED";
    blockedReason = t.error ?? `Task ${t.status.toLowerCase()}.`;
  } else if (t?.status === "DONE") {
    status = parseFindings(r.findings).length ? "COMPLETED" : "FAILED";
    blockedReason = status === "FAILED" ? "The task finished without recording findings." : null;
  } else if (t?.status === "RUNNING") {
    status = "RUNNING";
    blockedReason = null;
  } else if (t?.status === "QUEUED" && !getProvider()) {
    status = "BLOCKED";
    blockedReason = "AI provider NOT CONNECTED (ANTHROPIC_API_KEY). The research task is queued and starts once it is connected.";
  }
  if (status !== r.status || blockedReason !== r.blockedReason) return db.marketResearch.update({ where: { id }, data: { status, blockedReason, completedAt: status === "COMPLETED" ? new Date() : null } });
  return r;
}
