import { createElement } from "react";
import {
  Activity, AlertTriangle, BadgeCheck, Banknote, BarChart3, Bell, Blocks, Bot, Boxes, Brain, BrainCircuit, Building2, Calculator,
  CalendarClock, Camera, ChartPie, CheckCircle2, CircuitBoard, Cloud, CloudCog, Code2, Coins, Compass, Container, Cpu, CreditCard,
  Database, DatabaseZap, FileCheck2, FileSearch, FileText, Fingerprint, Gauge, GitBranch, GitMerge, Globe, Handshake, HardDrive,
  Headphones, HeartPulse, Home, KeyRound, Landmark, Languages, Layers, LayoutDashboard, LineChart, Link2, Lock, Mail, MessageSquare,
  Mic, Microscope, Network, Package, Palette, PiggyBank, Plug, Radar, Receipt, RefreshCcw, Repeat, Rocket, Route, Scale, ScanFace,
  ScanSearch, Search, Server, Settings2, Shield, ShieldCheck, ShoppingCart, Smartphone, Sparkles, SplitSquareHorizontal, Store,
  Target, Timer, TrendingUp, Truck, UserCheck, Users, Vault, Wallet, Webhook, Workflow, Wrench, Zap, type LucideIcon,
} from "lucide-react";

/** Keyword → icon rules, checked in order. Picks a meaningful icon for any card title. */
const rules: [RegExp, LucideIcon][] = [
  [/\b(kyc|kyb|identity|onboard|verif)/i, UserCheck],
  [/\b(aml|fraud|risk|sanction|threat|anomal)/i, Radar],
  [/\b(complian|regulat|audit|governance|policy|legal)/i, Scale],
  [/\b(pci|security|secure|protect|harden|zero.?trust|owasp|pentest)/i, ShieldCheck],
  [/\b(encrypt|key management|hsm|secret|vault|mpc|custody)/i, Vault],
  [/\b(auth|sso|oauth|access|permission|rbac|login)/i, KeyRound],
  [/\b(biometric|face|liveness)/i, ScanFace],
  [/\b(ledger|accounting|reconcil|double.entry|balance)/i, Calculator],
  [/\b(card|issuing|acquir|3-?d secure|checkout|pos\b)/i, CreditCard],
  [/\b(payment|payout|remit|transfer|settle|a2a|rail)/i, Banknote],
  [/\b(wallet)/i, Wallet],
  [/\b(lend|loan|credit|bnpl|underwrit)/i, PiggyBank],
  [/\b(bank|core banking|deposit|treasury)/i, Landmark],
  [/\b(invoice|billing|fee|pricing|receipt|subscription)/i, Receipt],
  [/\b(fx|currenc|exchange|trading|order book|matching|liquidity|market)/i, TrendingUp],
  [/\b(token|stablecoin|coin|rwa|nft|erc|mint)/i, Coins],
  [/\b(smart contract|solidity|protocol|chain|blockchain|onchain|on-chain|defi|dao|bridge|web3|node)/i, Blocks],
  [/\b(agent|copilot|assistant|chatbot|bot)\b/i, Bot],
  [/\b(llm|gpt|language model|fine.?tun|prompt|generative|genai)/i, BrainCircuit],
  [/\b(rag|retriev|search|semantic|knowledge)/i, FileSearch],
  [/\b(vision|image|ocr|camera|video)/i, Camera],
  [/\b(speech|voice|audio|transcri)/i, Mic],
  [/\b(nlp|translation|language)/i, Languages],
  [/\b(ml|machine learning|model|predict|forecast|train|inference|ai)\b/i, Brain],
  [/\b(evaluat|quality|test|qa\b|benchmark)/i, BadgeCheck],
  [/\b(automat|workflow|orchestrat|pipeline|process)/i, Workflow],
  [/\b(document|contract|form|report)/i, FileText],
  [/\b(analytic|insight|dashboard|metric|kpi|bi\b|reporting)/i, BarChart3],
  [/\b(data|warehouse|lake|etl|elt|stream|event)/i, Database],
  [/\b(real.?time|latency|performance|fast|speed|scale|throughput)/i, Gauge],
  [/\b(monitor|observab|alert|sre|reliab|uptime|incident)/i, Activity],
  [/\b(kubernetes|container|docker|cluster)/i, Container],
  [/\b(cloud|aws|azure|gcp|serverless|migrat|infra)/i, Cloud],
  [/\b(devops|ci\/cd|deploy|release|gitops|pipeline)/i, GitMerge],
  [/\b(platform engineering|internal platform|developer)/i, CloudCog],
  [/\b(backup|disaster|recovery|resilien|failover|redundan)/i, RefreshCcw],
  [/\b(cost|finops|budget|saving)/i, ChartPie],
  [/\b(api|sdk|integrat|webhook|connect|adapter|partner)/i, Plug],
  [/\b(microservice|architecture|modular|domain)/i, Boxes],
  [/\b(mobile|ios|android|app\b)/i, Smartphone],
  [/\b(web|portal|frontend|site)/i, Globe],
  [/\b(saas|multi.?tenant|tenant)/i, Layers],
  [/\b(admin|back.?office|console|operations)/i, LayoutDashboard],
  [/\b(design|ux|ui\b|brand|prototype)/i, Palette],
  [/\b(legacy|moderni|refactor|upgrade|rebuild)/i, Wrench],
  [/\b(mvp|launch|go.?live|startup|rollout)/i, Rocket],
  [/\b(strategy|discovery|roadmap|consult|assessment|advis)/i, Compass],
  [/\b(team|staff|engineer|talent|hire|squad|pod)/i, Users],
  [/\b(support|help|customer service)/i, Headphones],
  [/\b(notification|messag|email|chat)/i, MessageSquare],
  [/\b(ecommerce|commerce|shop|cart|marketplace|store)/i, ShoppingCart],
  [/\b(logistic|shipment|delivery|fleet|dispatch)/i, Truck],
  [/\b(health|patient|clinic|medical)/i, HeartPulse],
  [/\b(property|real estate)/i, Home],
  [/\b(schedul|booking|calendar)/i, CalendarClock],
  [/\b(research|experiment)/i, Microscope],
  [/\b(network|routing|route)/i, Route],
  [/\b(version|git|branch)/i, GitBranch],
  [/\b(enterprise|organi[sz]ation|company)/i, Building2],
  [/\b(storage|disk|file)/i, HardDrive],
  [/\b(config|custom|setting)/i, Settings2],
  [/\b(time|deadline|sla)/i, Timer],
  [/\b(goal|outcome|target|result)/i, Target],
  [/\b(collaborat|partner|relationship)/i, Handshake],
  [/\b(package|product)/i, Package],
  [/\b(link|interop)/i, Link2],
  [/\b(split|separat)/i, SplitSquareHorizontal],
  [/\b(repeat|recurr)/i, Repeat],
  [/\b(fingerprint|privacy|gdpr|consent)/i, Fingerprint],
  [/\b(error|failure|break|problem)/i, AlertTriangle],
  [/\b(check|verify|valid)/i, CheckCircle2],
  [/\b(hardware|iot|device|chip)/i, CircuitBoard],
  [/\b(compute|gpu|cpu)/i, Cpu],
  [/\b(server|host)/i, Server],
  [/\b(line|trend|growth)/i, LineChart],
  [/\b(inbox|mail)/i, Mail],
  [/\b(notify|bell)/i, Bell],
  [/\b(scan|detect)/i, ScanSearch],
  [/\b(search)/i, Search],
  [/\b(protection|shield)/i, Shield],
  [/\b(lock)/i, Lock],
  [/\b(store|merchant)/i, Store],
  [/\b(database|query)/i, DatabaseZap],
  [/\b(compliance doc|certif)/i, FileCheck2],
  [/\b(code|engineering|build|develop)/i, Code2],
  [/\b(network)/i, Network],
  [/\b(zap|instant)/i, Zap],
  [/\b(hook)/i, Webhook],
];

export function iconFor(...texts: (string | undefined)[]): LucideIcon {
  const text = texts.filter(Boolean).join(" ");
  for (const [re, icon] of rules) if (re.test(text)) return icon;
  return Sparkles;
}

export function AutoIcon({ title, hint, className }: { title: string; hint?: string; className?: string }) {
  // Title takes priority; description only used when the title alone gives no match.
  // Icons are static module-level components picked from a table, not created during render.
  let icon = iconFor(title);
  if (icon === Sparkles && hint) icon = iconFor(hint);
  return createElement(icon, { className, "aria-hidden": true, strokeWidth: 1.7 });
}
