/* Technology logos from simple-icons (CC0). Brand marks identify the technologies we build with; no partnership is implied. */
import {
  siAndroid,
  siAngular,
  siAnsible,
  siApacheairflow,
  siApachekafka,
  siApachespark,
  siApple,
  siArgo,
  siBnbchain,
  siChainlink,
  siClickhouse,
  siCloudflare,
  siDjango,
  siDocker,
  siDotnet,
  siElasticsearch,
  siEthereum,
  siEthers,
  siExpress,
  siFastapi,
  siFirebase,
  siFlask,
  siFlutter,
  siGithubactions,
  siGitlab,
  siGo,
  siGooglebigquery,
  siGooglecloud,
  siGrafana,
  siGraphql,
  siHuggingface,
  siIpfs,
  siJavascript,
  siJenkins,
  siKeycloak,
  siKotlin,
  siKubernetes,
  siLangchain,
  siLaravel,
  siLinux,
  siMariadb,
  siMlflow,
  siMongodb,
  siMysql,
  siNestjs,
  siNextdotjs,
  siNginx,
  siNodedotjs,
  siNvidia,
  siOpenapiinitiative,
  siOpencv,
  siOpenid,
  siOpenjdk,
  siOpensearch,
  siOpenzeppelin,
  siOptimism,
  siOwasp,
  siPhp,
  siPolygon,
  siPostgresql,
  siPrometheus,
  siPython,
  siPytorch,
  siQdrant,
  siRabbitmq,
  siReact,
  siRedis,
  siRemix,
  siRust,
  siSnowflake,
  siSocketdotio,
  siSolana,
  siSolidity,
  siSpacy,
  siSpringboot,
  siSqlite,
  siSupabase,
  siSvelte,
  siSwift,
  siTailwindcss,
  siTerraform,
  siTypescript,
  siVault,
  siVuedotjs,
  siWagmi,
  siWalletconnect,
  siWeb3dotjs,
  siXrp,
  type SimpleIcon,
} from "simple-icons";

export const techLogo: Record<string, SimpleIcon> = {
  "react": siReact,
  "nextjs": siNextdotjs,
  "vue": siVuedotjs,
  "angular": siAngular,
  "svelte": siSvelte,
  "javascript": siJavascript,
  "typescript": siTypescript,
  "tailwind": siTailwindcss,
  "nodejs": siNodedotjs,
  "nestjs": siNestjs,
  "express": siExpress,
  "python": siPython,
  "django": siDjango,
  "fastapi": siFastapi,
  "flask": siFlask,
  "java": siOpenjdk,
  "spring-boot": siSpringboot,
  "go": siGo,
  "rust": siRust,
  "php": siPhp,
  "laravel": siLaravel,
  "dotnet": siDotnet,
  "flutter": siFlutter,
  "react-native": siReact,
  "swift": siSwift,
  "swiftui": siSwift,
  "kotlin": siKotlin,
  "android": siAndroid,
  "ios": siApple,
  "ethereum": siEthereum,
  "bnb-chain": siBnbchain,
  "polygon": siPolygon,
  "solana": siSolana,
  "optimism": siOptimism,
  "xrp-ledger": siXrp,
  "solidity": siSolidity,
  "remix": siRemix,
  "openzeppelin": siOpenzeppelin,
  "ethersjs": siEthers,
  "web3js": siWeb3dotjs,
  "wagmi": siWagmi,
  "walletconnect": siWalletconnect,
  "ipfs": siIpfs,
  "chainlink": siChainlink,
  "google-cloud": siGooglecloud,
  "cloudflare": siCloudflare,
  "nginx": siNginx,
  "linux": siLinux,
  "docker": siDocker,
  "kubernetes": siKubernetes,
  "terraform": siTerraform,
  "ansible": siAnsible,
  "github-actions": siGithubactions,
  "gitlab-ci": siGitlab,
  "jenkins": siJenkins,
  "argocd": siArgo,
  "prometheus": siPrometheus,
  "grafana": siGrafana,
  "postgresql": siPostgresql,
  "mysql": siMysql,
  "mongodb": siMongodb,
  "redis": siRedis,
  "sqlite": siSqlite,
  "mariadb": siMariadb,
  "firestore": siFirebase,
  "elasticsearch": siElasticsearch,
  "opensearch": siOpensearch,
  "clickhouse": siClickhouse,
  "snowflake": siSnowflake,
  "bigquery": siGooglebigquery,
  "supabase": siSupabase,
  "kafka": siApachekafka,
  "rabbitmq": siRabbitmq,
  "redis-streams": siRedis,
  "spark": siApachespark,
  "airflow": siApacheairflow,
  "owasp": siOwasp,
  "hashicorp-vault": siVault,
  "keycloak": siKeycloak,
  "graphql": siGraphql,
  "openapi": siOpenapiinitiative,
  "websockets": siSocketdotio,
  "oauth2": siOpenid,
  "llm": siHuggingface,
  "fine-tuning": siPytorch,
  "mlops": siMlflow,
  "ai-inference": siNvidia,
  "vector-databases": siQdrant,
  "rag": siLangchain,
  "ai-agents": siLangchain,
  "computer-vision": siOpencv,
  "nlp": siSpacy,
};
