import "server-only";
import { z } from "zod";
import { db } from "@/lib/db/client";
import { dealRisks, leadPriorities, nextBestActions, salesForecast } from "@/lib/company/sales";
import { clientHealth, collectionsQueue, projectHealth } from "@/lib/company/delivery";
import type { ToolDef } from "./tools";

/**
 * Operations tools (sales, delivery, internal systems). Reads come from live records. The only writes are an AI
 * screening summary saved as a draft on a candidate (never a hiring decision) and purchase-request / risk proposals,
 * which are approval-governed like every other write.
 */
const def = <S extends z.ZodType>(t: ToolDef<S>) => t as unknown as ToolDef;
const id = z.string().trim().min(1).max(40);
const lim = z.number().int().min(1).max(50).default(15);

export const OPS_TOOLS: ToolDef[] = [
  // ─── sales ───
  def({ name: "getSalesPriorities", description: "Open leads ranked by qualification score, website intent, priority, freshness and overdue follow-ups — with the reasons for each rank.", input: z.object({ limit: lim }), permissions: ["leads:view"], kind: "read", risk: "LOW", run: async (_c, i) => { const r = await leadPriorities(i.limit); return { data: r, records: r.map((x) => `Lead:${x.id}`) }; } }),
  def({ name: "getNextBestActions", description: "Next best sales actions from record state: uncontacted new leads, overdue follow-ups, proposals missing in late stages, stalled deals, passed close dates, meeting preparation.", input: z.object({ limit: lim }), permissions: ["leads:view", "deals:view"], kind: "read", risk: "LOW", run: async (_c, i) => ({ data: await nextBestActions(i.limit) }) }),
  def({ name: "getDealRisks", description: "Open deals with a 0–100 risk score and the signals behind it (stalled time, passed close date, late stage without proposal, low probability, no updates).", input: z.object({ limit: lim }), permissions: ["deals:view"], kind: "read", risk: "LOW", run: async (_c, i) => { const r = await dealRisks(i.limit); return { data: r, records: r.map((x) => `Deal:${x.id}`) }; } }),
  def({ name: "getSalesForecast", description: "ESTIMATED pipeline forecast by expected close month and currency (value × stage probability), with the real 12-month win rate for calibration.", input: z.object({}), permissions: ["deals:view"], kind: "read", risk: "LOW", run: async () => ({ data: { ...(await salesForecast()), note: "Weighted values are estimates; never add different currencies." } }) }),
  // ─── delivery ───
  def({ name: "getProjectHealth", description: "Active projects with computed health (GREEN/AMBER/RED) from overdue and blocked tasks, missed milestones, open issues and target date, next to the recorded health.", input: z.object({}), permissions: ["projects:view"], kind: "read", risk: "LOW", run: async () => { const r = await projectHealth(); return { data: r, records: r.map((x) => `Project:${x.id}`) }; } }),
  def({ name: "getClientHealth", description: "Active clients scored 0–100 from SLA breaches, open tickets, overdue invoices and red projects (HEALTHY / WATCH / AT_RISK).", input: z.object({}), permissions: ["clients:view"], kind: "read", risk: "LOW", run: async () => { const r = await clientHealth(); return { data: r, records: r.map((x) => `Client:${x.id}`) }; } }),
  def({ name: "getCollectionsQueue", description: "Overdue invoices ordered by days overdue, with balance per currency. Reminder emails go through sendEmail (always approval).", input: z.object({ limit: lim }), permissions: ["finance:view"], kind: "read", risk: "LOW", run: async (_c, i) => { const r = await collectionsQueue(i.limit); return { data: r, records: r.map((x) => `Invoice:${x.id}`) }; } }),
  // ─── recruiting ───
  def({ name: "listOpenRoles", description: "Open roles with candidate counts by stage.", input: z.object({}), permissions: ["employees:view"], kind: "read", risk: "LOW", run: async () => { const rows = await db.jobOpening.findMany({ where: { status: { in: ["OPEN", "ON_HOLD"] } }, include: { candidates: { select: { stage: true } } } }); return { data: rows.map((j) => ({ id: j.id, title: j.title, status: j.status, location: j.location, candidates: j.candidates.reduce<Record<string, number>>((a, c) => ({ ...a, [c.stage]: (a[c.stage] ?? 0) + 1 }), {}) })), records: rows.map((j) => `JobOpening:${j.id}`) }; } }),
  def({ name: "listCandidates", description: "Candidates entered by the team for a role (or all), with stage, notes and any earlier AI screening summary.", input: z.object({ jobId: id.optional(), stage: z.string().trim().max(20).optional(), limit: lim }), permissions: ["employees:view"], kind: "read", risk: "LOW", run: async (_c, i) => { const rows = await db.candidate.findMany({ where: { jobId: i.jobId, stage: i.stage }, take: i.limit, orderBy: { createdAt: "desc" }, select: { id: true, name: true, stage: true, source: true, notes: true, resumeText: true, aiSummary: true, job: { select: { title: true, description: true } } } }); return { data: rows.map((r) => ({ ...r, resumeText: r.resumeText?.slice(0, 6000) ?? null })), records: rows.map((r) => `Candidate:${r.id}`) }; } }),
  def({ name: "screenCandidate", description: "Save an AI screening summary for a candidate against the role: evidence-based strengths and gaps from the resume/notes only. A draft for the hiring manager — it never changes the candidate's stage. Never infer age, gender, ethnicity, religion, health or other protected characteristics.", input: z.object({ candidateId: id, summary: z.string().trim().min(20).max(3000), strengths: z.array(z.string().trim().max(200)).max(8).default([]), gaps: z.array(z.string().trim().max(200)).max(8).default([]) }), permissions: ["employees:manage"], kind: "draft", stores: true, risk: "LOW", run: async (c, i) => { const text = [`AI screening (draft by ${c.agentSlug}, ${new Date().toISOString().slice(0, 10)}):`, i.summary, i.strengths.length ? `Strengths: ${i.strengths.join("; ")}` : "", i.gaps.length ? `Gaps to probe: ${i.gaps.join("; ")}` : "", "Decision: to be made by the hiring manager."].filter(Boolean).join("\n"); await db.candidate.update({ where: { id: i.candidateId }, data: { aiSummary: text } }); return { data: { storedForReview: `screening summary on candidate ${i.candidateId}` }, records: [`Candidate:${i.candidateId}`] }; } }),
  // ─── procurement ───
  def({ name: "listPurchaseRequests", description: "Vendors and purchase requests with status (SUBMITTED / APPROVED / ORDERED …). Nothing is ever bought or paid by the system.", input: z.object({ status: z.string().trim().max(20).optional(), limit: lim }), permissions: ["finance:view"], kind: "read", risk: "LOW", run: async (_c, i) => { const [reqs, vendors] = await Promise.all([db.purchaseRequest.findMany({ where: { status: i.status }, take: i.limit, orderBy: { createdAt: "desc" }, include: { vendor: { select: { name: true, riskLevel: true } } } }), db.vendor.findMany({ take: 50, select: { id: true, name: true, status: true, riskLevel: true, category: true } })]); return { data: { requests: reqs.map((r) => ({ id: r.id, title: r.title, status: r.status, amount: r.amount?.toString() ?? null, currency: r.currency, vendor: r.vendor?.name ?? null })), vendors } }; } }),
  def({ name: "proposePurchaseRequest", description: "Propose a purchase request (title, vendor, amount, justification). Becomes a SUBMITTED request only after a person approves; approving the purchase itself is a separate human decision.", input: z.object({ title: z.string().trim().min(3).max(200), vendorId: id.optional(), amount: z.number().positive().max(10_000_000).optional(), currency: z.string().trim().length(3).default("USD"), justification: z.string().trim().min(10).max(4000) }), permissions: ["finance:view"], kind: "write", risk: "MEDIUM", preview: async (i) => ({ summary: `Submit purchase request "${i.title}"${i.amount ? ` (${i.amount} ${i.currency})` : ""}`, affected: [], content: i.justification }), run: async (c, i) => { const r = await db.purchaseRequest.create({ data: { title: i.title, vendorId: i.vendorId ?? null, amount: i.amount != null ? i.amount.toFixed(2) : null, currency: i.currency.toUpperCase(), justification: i.justification, status: "SUBMITTED", requestedById: c.user.id === "system" ? null : c.user.id } }); return { data: { id: r.id, status: r.status }, records: [`PurchaseRequest:${r.id}`] }; } }),
  // ─── compliance & risk ───
  def({ name: "getComplianceRegister", description: "Compliance / legal-operations checklist items (framework, owner, due date, status) and overdue items.", input: z.object({}), permissions: ["contracts:view"], kind: "read", risk: "LOW", run: async () => { const rows = await db.complianceItem.findMany({ orderBy: [{ status: "asc" }, { dueDate: "asc" }], take: 100 }); return { data: { items: rows, overdue: rows.filter((r) => r.dueDate && r.dueDate < new Date() && !["DONE", "NOT_APPLICABLE"].includes(r.status)).length } }; } }),
  def({ name: "getRiskRegister", description: "Risk register sorted by score (likelihood × impact, 1–25) with owner, mitigation and status.", input: z.object({}), permissions: ["contracts:view"], kind: "read", risk: "LOW", run: async () => { const rows = await db.riskItem.findMany({ where: { status: { not: "CLOSED" } }, take: 100 }); return { data: rows.map((r) => ({ ...r, score: r.likelihood * r.impact })).sort((a, b) => b.score - a.score) }; } }),
  def({ name: "proposeRisk", description: "Propose a new risk-register entry (likelihood and impact 1–5, mitigation). Added only after a person approves.", input: z.object({ title: z.string().trim().min(5).max(200), category: z.string().trim().max(60).optional(), likelihood: z.number().int().min(1).max(5), impact: z.number().int().min(1).max(5), mitigation: z.string().trim().max(4000).optional() }), permissions: ["contracts:manage"], kind: "write", risk: "MEDIUM", preview: async (i) => ({ summary: `Add risk "${i.title}" (score ${i.likelihood * i.impact})`, affected: [], content: i.mitigation }), run: async (c, i) => { const r = await db.riskItem.create({ data: { title: i.title, category: i.category ?? null, likelihood: i.likelihood, impact: i.impact, mitigation: i.mitigation ?? null, ownerSlug: c.agentSlug } }); return { data: { id: r.id }, records: [`RiskItem:${r.id}`] }; } }),
];
